<a href="https://colab.research.google.com/github/RitikaAg/thomasSimonini_RLCourse/blob/master/OpenAITaxiv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install gym

In [0]:
import numpy as np,gym,random

In [4]:
env=gym.make("Taxi-v2")
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [8]:
action_size=env.action_space.n
state_size=env.observation_space.n
qtable=np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [0]:
t_episodes=50000
test_episodes=100
max_steps=99
alpha=.7
gamma=.618
ep=1
max_ep=1
d_rate=.01
min_ep=.01

In [0]:
for episode in range(t_episodes):
  state=env.reset()
  done=False
  step=0
  for step in range(max_steps):
    e_E_tradeoff=random.uniform(0,1)
    if(e_E_tradeoff>ep):
      action=np.argmax(qtable[state,:])
    else:
      action=env.action_space.sample()
    new_state,reward,done,info=env.step(action)
    qtable[state,action]=qtable[state,action]+alpha*(reward+gamma*np.max(qtable[new_state,:])-qtable[state,action])
    state=new_state
    if done==True:
      break
    episode+=1
    ep=min_ep+(max_ep-min_ep)*np.exp(-d_rate*ep)
    
    

In [15]:
env.reset()
rewards=[]
for episode in range(test_episodes):
  state=env.reset()
  done=False
  step=0
  t_rewards=0
  print("*********************")
  print("EPISODE",episode)
  for step in range(max_steps):
    env.render()
    action=np.argmax(qtable[state,:])
    new_state,reward,done,info=env.step(action)
    t_rewards+=reward
    if done:
      rewards.append(t_rewards)
      print("Score",t_rewards)
      break
    state=new_state
env.close()
print("ScoreOvertime"+str(sum(rewards)/test_episodes))
    
  

*********************
EPISODE 0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
|_: : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| :_: : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : :_: : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: |_: :G|
| : : : : |
| : : 